baseurl                 = "https://itsalocke.com/blog/"
languageCode            = "en-gb"
title                   = "Locke Data Blog"
theme                   = "hugo-lockedata-blog"


[permalinks]
  posts = "/:title/"
  page                = "/:title/"

[taxonomies]
    tag                 = "tags"
    category            = "categories"
	status              = "statuses"

# The header menu will appear as an inline-list at the top right of the page
[[languages.en.menu.prepend]]
    name                = "Locke Data"
    weight              = 1
    url                 = "https://itsalocke.com"

[[languages.en.menu.prepend]]
    name                = "Blog"
    weight              = 2
    url                 = "https://itsalocke.com/blog/"

# The footer menu will appear as an inline-list at the bottom left of the footer found at the bottom of the screen
  # Footer
  [params.footer]
    enable = true

  [[languages.en.menu.social]]
    weight = 10
    name = "twitter"
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://twitter.com/lockedata"
  [[languages.en.menu.social]]
    weight = 20
    name = "facebook"
    pre = "<i class='fa fa-facebook'></i>"
    url = "https://facebook.com/lockedata"
  [[languages.en.menu.social]]
    weight = 30
    name = "linkedin"
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://linkedin.com/company/locke-data"
  [[languages.en.menu.social]]
    weight = 40
    name = "github"
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/lockedata"
  [[languages.en.menu.footer]]
    weight = 20
    name = "Legalese and stuff"
    url = "https://itsalocke.com/company/policies"
  [[languages.en.menu.footer]]
    weight = 10
    name = "RSS"
    url = "index.xml"
  [[languages.en.menu.footer]]
    weight = 30
    name = "Bug Bounty"
    url = "https://goo.gl/forms/KQiYR201Fcn4k9Zh2"
[params]
    keywords            = ["data science", "consultancy", "predictive analytics", "advanced analytics"]
    description         = "Locke Data helps organisations get started with data science. Grow your skills with our blog posts."
    google_analytics    = "UA-58415537-1"
    google_adsense      = "ca-pub-XXXXXX"
    disqus              = "itsalocke"
    google_webmaster    = ""
    bing_webmaster      = ""
    alexa               = ""
    favicon             = ""
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.'

  [params.navigation]
    # Optional brand logo used in nav stored in 'static/img/'.
    logo = "LockeDataTextNew.svg"
	
# Social media icons and links that appear in the footer
[social]
    twitter             = "lockedata"
    googleplus          = ""
    linkedin            = "https://www.linkedin.com/in/NAME_HERE"
    youtube             = "https://www.youtube.com/users/NAME_HERE"
    paypal              = ""
    instagram           = ""
    reddit              = ""
    email               = ""
    pinterest           = ""
    wordpress           = ""
